version: "3.8"

services:
  web:
    build: ./smarthome
    image: &web smarthome
    container_name: smarthome
    command: sh -c "python manage.py makemigrations; python manage.py migrate; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./smarthome/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=smarthome
      - POSTGRES_PASSWORD=smarthome
      - POSTGRES_DB=smarthome

  rabbit:
    image: library/rabbitmq:3.8-management
    container_name: smarthome-rabbit
    hostname: dimatroickij
    env_file:
      - .env.dev
    ports:
      - 15672:15672
      - 5672:5672

  celery:
    image: *web
    container_name: smarthome-celery
    env_file:
      - .env.dev
    command: celery worker -A smarthome
    volumes:
      - ./smarthome:/usr/src/app
    depends_on:
      - rabbit
      - db
    links:
      - rabbit
      - db

  celery_beat:
    image: *web
    container_name: smarthome-celery_beat
    env_file:
      - .env.dev
    command: celery -A smarthome beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile=/tmp/celeryd.pid
    volumes:
      - ./smarthome:/usr/src/app
    depends_on:
      - rabbit
      - db
    links:
      - rabbit
      - db

volumes:
  postgres_data:
