version: "3.3"
services:
  web:
    image: "${IMAGE}:smarthome"
    container_name: smarthome
    command: sh -c "python manage.py makemigrations --noinput; python manage.py migrate; python manage.py collectstatic --no-input --clear; gunicorn smarthome.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/static
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file:
      - .env

#  nginx:
#    image: "${IMAGE}:smarthome-nginx"
#    container_name: smarthome-nginx
#    volumes:
#      - static_volume:/static
#      - media_volume:/usr/src/app/mediafiles
#      - /certs:/etc/nginx/certs
#    ports:
#      - 80:80
#      - 443:443
#    env_file:
#      - .env
#    depends_on:
#      - web

  rabbit:
    image: library/rabbitmq:3.8-alpine
    container_name: smarthome-rabbit
    hostname: dimatroickij
    env_file:
      - .env
    expose:
      - 15672
      - 5672

  celery:
    image: "${IMAGE}:smarthome"
    container_name: smarthome-celery
    env_file:
      - .env
    command: celery worker -A smarthome
    depends_on:
      - rabbit
      - web
    links:
      - rabbit

  celery_beat:
    image: "${IMAGE}:smarthome"
    container_name: smarthome-celery_beat
    env_file:
      - .env
    command: celery -A smarthome beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - rabbit
      - web
    links:
      - rabbit

volumes:
  static_volume:
  media_volume:

networks:
  default:
    external:
      name: nginx-proxy