version: "3.3"

services:
  web:
    build:
      context: ./smarthome
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    container_name: web
    command: sh -c "python manage.py collectstatic --no-input --clear"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file: 
      - .env

  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/mediafiles
      - /certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  rabbit:
    image: library/rabbitmq:3.8-alpine
    container_name: rabbit
    hostname: dimatroickij
    env_file:
      - .env
    ports:
    - 15672:15672
    - 5672:5672

  celery:
    build:
      context: ./smarthome
      cache_from:
        - "${CELERY_IMAGE}"
    image: "${CELERY_IMAGE}"
    container_name: celery
    env_file:
      - .env
    command: celery worker -A smarthome
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/mediafiles
    depends_on:
      - rabbit
      - web
    links:
      - rabbit

  celery_beat:
    build:
      context: ./smarthome
      cache_from:
        - "${CELERY_BEAT_IMAGE}"
    image: "${CELERY_BEAT_IMAGE}"
    container_name: celery_beat
    env_file:
      - .env
    command: celery -A smarthome beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/mediafiles
    depends_on:
      - rabbit
      - web
    links:
      - rabbit

volumes:
  static_volume:
  media_volume:

