#!/bin/sh

echo DEBUG=$DEBUG >> .env
echo SQL_ENGINE=$SQL_ENGINE >> .env
echo SECRET_KEY=$SECRET_KEY >> .env
echo SQL_DATABASE=$SQL_DATABASE >> .env
echo SQL_USER=$SQL_USER >> .env
echo SQL_PASSWORD=$SQL_PASSWORD >> .env
echo SQL_HOST=$SQL_HOST >> .env
echo SQL_PORT=$SQL_PORT >> .env
echo DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS >> .env
echo WEB_IMAGE=$IMAGE:web  >> .env
echo NGINX_IMAGE=$IMAGE:nginx  >> .env
echo RABBIT_IMAGE=$IMAGE:rabbit  >> .env
echo CELERY_IMAGE=$IMAGE:celery  >> .env
echo CELERY_BEAT_IMAGE=$IMAGE:celery_beat  >> .env
echo CI_REGISTRY_USER=$CI_REGISTRY_USER   >> .env
echo CI_JOB_TOKEN=$CI_JOB_TOKEN  >> .env
echo CI_REGISTRY=$CI_REGISTRY  >> .env
echo IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME >> .env
echo RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER >> .env
echo RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS >> .env
echo CELERY_BROKER_URL=$CELERY_BROKER_URL >> .env
echo CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND >> .env
echo CELERY_TIMEZONE=$CELERY_TIMEZONE >> .env