# Generated by Django 3.1.2 on 2020-10-04 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='user_id')),
                ('device_class', models.CharField(max_length=255, verbose_name='Класс устройства')),
                ('friendly_name', models.CharField(max_length=255, verbose_name='friendly_name')),
                ('icon', models.CharField(blank=True, max_length=255, verbose_name='Иконка')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=255, verbose_name='unit_of_measurement')),
                ('entity_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='entity_id')),
            ],
        ),
    ]
