# Generated by Django 3.1.2 on 2020-10-22 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSmarthome',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(choices=[('guest', 'Гость'), ('owner', 'Владелец')], max_length=5, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'уровень доступа к умному дому',
                'verbose_name_plural': 'Уровень доступа к умному дому',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Smarthome',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('token', models.CharField(max_length=255, verbose_name='Token умного дома')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание умного дома')),
            ],
            options={
                'verbose_name': 'Умный дом',
                'verbose_name_plural': 'умные дома',
                'ordering': ['url'],
            },
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.AddField(
            model_name='accesssmarthome',
            name='smarthome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.smarthome', verbose_name='ID умного дома'),
        ),
        migrations.AddField(
            model_name='accesssmarthome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='accesssmarthome',
            unique_together={('smarthome', 'user')},
        ),
    ]
