# Generated by Django 3.1.2 on 2020-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssmarthome',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='Доступ удалён'),
        ),
        migrations.AddField(
            model_name='device',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='Устройство удалено'),
        ),
        migrations.AddField(
            model_name='smarthome',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='Дом удалён'),
        ),
    ]
