# Generated by Django 3.1.2 on 2020-11-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20201105_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssmarthome',
            name='isConfirmed',
            field=models.BooleanField(default=False, verbose_name='Пользователь подтвердил запрос'),
        ),
    ]
