# Generated by Django 3.1.3 on 2020-11-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_accesssmarthome_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smarthome',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
    ]
