# Generated by Django 3.1.3 on 2020-11-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20201107_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smarthome',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
