# Generated by Django 3.1.3 on 2020-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20201107_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smarthome',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterUniqueTogether(
            name='smarthome',
            unique_together={('url', 'isDelete')},
        ),
    ]
