# Generated by Django 3.1.3 on 2020-11-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20201107_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smarthome',
            name='isDelete',
        ),
    ]
