# Generated by Django 3.1.3 on 2020-11-08 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idDevice', models.CharField(max_length=255, unique=True, verbose_name='ID устройства в HomeAssistant')),
                ('entity_id', models.CharField(max_length=255, unique=True, verbose_name='ID для изменения состояния устройства')),
                ('device_class', models.CharField(max_length=255, null=True, verbose_name='Класс устройства')),
                ('friendly_name', models.CharField(max_length=255, verbose_name='Название из HomeAssistant')),
                ('name', models.CharField(blank=True, default=models.CharField(max_length=255, verbose_name='Название из HomeAssistant'), max_length=255, null=True, verbose_name='Введённоё название устройства')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка для сенсоров')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица измерения')),
                ('smarthome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.smarthome', verbose_name='ID умного дома')),
            ],
            options={
                'verbose_name': 'устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['idDevice'],
            },
        ),
    ]
