# Generated by Django 3.1.3 on 2020-11-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20201108_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestates',
            options={'ordering': ['-last_updated'], 'verbose_name': 'состояние устройства', 'verbose_name_plural': 'Состояния устройств'},
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Введённоё название устройства'),
        ),
    ]
