# Generated by Django 3.1.3 on 2020-11-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20201108_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestates',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Состояние устройства'),
        ),
    ]
