# Generated by Django 3.1.3 on 2020-11-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20201109_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='domain',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domain'),
        ),
    ]
