# Generated by Django 3.1.3 on 2020-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_device_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='domain',
            field=models.CharField(max_length=255, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='device',
            name='entity_id',
            field=models.CharField(max_length=255, verbose_name='ID для изменения состояния устройства'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('entity_id', 'domain')},
        ),
    ]
