# Generated by Django 3.1.3 on 2020-11-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20201109_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='entity_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID для изменения состояния устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='domain',
            field=models.CharField(max_length=255, verbose_name='Domain'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('entity_id', 'domain')},
        ),
        migrations.RemoveField(
            model_name='device',
            name='codeDevice',
        ),
    ]
