# Generated by Django 3.1.3 on 2020-11-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20201109_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='domain',
        ),
    ]
